package com.example.finalproject;
//This class allows the database handler to create new Alerts and modify them.
public class Alerts {
    //Define variables that every alert will have inside the database
    int _id;
    String _category;
    String _amount;
    public Alerts(){   }

    public Alerts(int id, String category, String amount){
        //Initialize an Alert.
        this._id = id;
        this._category = category;
        this._amount = amount;
    }

    public Alerts(String category, String amount){
        //Only change category and amount. It doesn't include ID since it is autogenerated.
        this._category = category;
        this._amount = amount;
    }

    public int getID(){
        //Method to get the ID value
        return this._id;
    }

    public void setID(int id){
        //Method to change the ID value
        this._id = id;
    }


    public String getCategory(){
        //Method to get the category value
        return this._category;
    }
    //Method to change the category value
    public void setCategory(String category){ this._category = category; }

    
    public String getAmount(){
        //Method to get the amount value for an alert
        return this._amount;
    }
    //Method to change the amount value of an alert
    public void setAmount(String amount){ this._amount = amount; }

}
